# Generated by Django 4.2.1 on 2023-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='작성자')),
                ('message', models.TextField(verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
            ],
        ),
    ]
