# Generated by Django 4.2.1 on 2023-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='작성자')),
                ('message', models.TextField(verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
            ],
        ),
    ]
